sudo: required
dist: bionic
language: java
jdk: openjdk8
jobs:
  include:
    - name: oap-shuffle-remote-shuffle
      before_install:
              - MAVEN_OPTS="-Xmx2948m"        
      install:
      - #empty install step
      script:
      - mvn clean install
