sudo: required
dist: bionic
language: java
jdk: openjdk8
jobs:
  include:
    - name: oap-shuffle-remote-shuffle
      before_install:
      - echo "MAVEN_OPTS='-Xmx2948m'" > ~/.mavenrc        
      install:
      - #empty install step
      script:
      - mvn -q clean install
